convo = [
 "Assalam o alaikum",
 "Walikum salam",
 "hello",
 "hello,Welcome",
 "hy",
 "hy,Welcome",
 "hi",
 "hi,Welcome",
 "hlo",
 "hlo,Welcome",
 "What is your name?",
 "My name is Bot created by Hammad",
 "How are you ?",
 "I am bot created by Hammad",
 "What are you doing these day",
 "Doing great",
 "Thankyou",
 "NO Problem",
 "In which city you live?",
 "I live in Kamalia",
 "In which language to talk?",
 "I mostly talk in english",
 "What is university?",
 "An institution of higher learning providing facilities for teaching and research and authorized to grant academic degrees.",
 "How do I choose the right university for me?",
 "Choosing the right university can be a challenging decision. Start by considering factors such as location,campus size, academic programs, student life, and cost. Research different universities online and consider visiting campuses in person to get a better sense of the campus culture and environment.Don't forget to consider factors such as extracurricular activities,career services and opportunities for research or study abroad.",
 "What is UAF?",
 "Uaf stand for University of Agriculture Faisalabad is a public research university located in Faisalabad, Pakistan and sub Campus in Different cities Toba, Bura wala etc. It is one of the oldest and most prestigious agricultural universities in the country, offering undergraduate and graduate programs in various fields.",
 "What programs are offered at the UAF?",
 "The university offers undergraduate, graduate, and postgraduate programs in various fields, including agriculture, veterinary sciences, food sciences, environmental sciences, social sciences, and more.",
 "How can I apply for admission to the University Agriculture Faisalabad and sab Campus?",
 "You can apply for admission to the UAF by visiting their official website and submitting an online application form. You may also be required to appear in an entry test and fulfill other admission requirements.",
 "What are the admission requirements for the University of Agriculture Faisalabad or sub campus?",
 "The admission requirements for the University of Agriculture Faisalabad and sub campuses vary depending on the program you are interested in. Generally, you must have completed your intermediate or equivalent with at least 50% marks, appear in an entry test, have a domicile of Punjab province, and full fill the other Addmission requirement.",
 "What is the duration of the programs offered at the University of Agriculture Faisalabad?",
 "The duration of the programs offered at the University of Agriculture Faisalabad varies depending on the program. Generally, undergraduate programs take four years to complete, and postgraduate programs take one to three years to complete.",
 "Does the University of Agriculture Faisalabad offer scholarships?",
 "Yes, the University of Agriculture Faisalabad offers scholarships to deserving and needy students. These scholarships is merit-based or need-based and cover tuition fees, accommodation, and other expenses.",
 "How I can apply for Scholarship in UAF?",
 "For Scholarship you need to full fill the Application Forms for Scholarship. you get a form a online on web site uaf.edu.pk.",
 "What facilities are available for students at the University of Agriculture Faisalabad?",
 "The University of Agriculture Faisalabad has various facilities for students, including a library, computer labs, sports facilities, medical facilities, and more. The university also has hostels for male and female students.",
 "What is the ranking of UAF?",
 "UAF is ranked among the top universities in Pakistan in the fields of agriculture and veterinary sciences. It is also recognized internationally for its research and academic programs.",
 "What is the campus life like at the University of Agriculture Faisalabad?",
 "The University of Agriculture Faisalabad has a vibrant campus life with a range of extracurricular activities, sports facilities, clubs, and societies. The campus is also home to various cafes, restaurants, and shops.",
 "Does the University of Agriculture Faisalabad offer research opportunities?",
 "Yes, the University of Agriculture Faisalabad has a strong research program and offers research opportunities for students and faculty in various fields.",
 "What are the facilities available at the University of Agriculture Faisalabad?",
 "The University of Agriculture Faisalabad has modern facilities and infrastructure, including libraries, computer labs, research centers, sports facilities, and student accommodation.",
 "What is the university's vision and mission?",
 "The University of Agriculture Faisalabad vision is to become a world-class university in agricultural education, research, and outreach. Its mission is to produce skilled and competent graduates and to advance knowledge and technology in the fields of agriculture and related sciences.",
 "What is the tuition fee at UAF?",
 "The tuition fee at UAF varies depending on the program you are enrolled in. However, UAF is a public university, and the tuition fee is generally lower than that of private universities in Pakistan.",
 "How much does it cost to attend university?",
 "The cost of attending university varies widely depending on the program you are interested in. But this is not always the case.You should also consider the cost of board,books,supplies and any other fees.Be sure to research the cost of attending each university you are interested in and explore financial aid options.",
 "What kind of Internship Program in UAF?",
 "An internship is a work-related learning experience for students who wish to develop hands on work experience in a certain occupational field. Most internships are temporary assignments, can be shorter or longer depending upon the program requirements. These may be paid, unpaid or partially (in the form of a stipend). University is making its all out efforts to arrange paid internships for the students in coordination with Government Departments/private organizations.",
 "What resources are available to help me succeed academically in UAF?",
 "The University of Agriculture Faisalabad provides various resources and support services to help students succeed academically. Academic Advisors, Libraries, Computer Labs, Study Groups, Tutoring Services, Writing Centers, Workshops and Seminars and Career Services.Students are encouraged to take advantage of these resources and seek help whenever they need it.",
 "What types of student clubs and organizations are available in UAF?",
 "For carrying on co-curricular activities, we have established very well-organized and well-managed student potential Groups/Clubs which include Qiraat & Naat Club, The Debating Club, The Quiz Club, Society of Agriculture Writers, The Art Club, UAF Media Club, Virsa Musical Society, Character Building Society, Young Development Club, and Rotary Club.",
 "How do I prepare for graduate university?",
 "Preparing for graduate university involves researching potential programs,studying for graduate admissions tests such in the UAF and building relationships with professors who can provide recommendation letters",
 "How do I balance academics, extracurricular activities, and social life?",
 "Balancing academic,extracurricular,and social responsibilities can be challenging,but planning and time management can help.Setting priorities,creating a schedule and seeking support when needed can also be helpful.",
 "What resources are available for mental health and wellness support?",
 "University often have counseling centers and other resources available to support student's mental health and wellness.Students can also seek support from peer support groups or local mental health professionals.",
 "Top universities in Pakistan?",
 "According to the Higher Education Commission of Pakistan,Top University in Pakistan. National University of Sciences and Technology (NUST), Quaid-i-Azam University (QAU), Lahore University of Management Sciences (LUMS), Pakistan Institute of Engineering and Applied Sciences (PIEAS), University of the Punjab, University of Agriculture Faisalabad (UAF), Aga Khan University, University of Health Sciences Lahore, COMSATS University Islamabad (CUI), National College of Arts (NCA).",
 "How can I contact the university admissions department of UAF?",
 "All candidates, can contact through visiting Registrar's Office. All candidates also contact the admissions department via email(registrar@uaf.edu.pk) and Fax(+92-41-9200764).",
 "Does the University have different standards of education for various provinces?",
 "Absolutely not. The University provides uniform education to all its students regardless of their geographical locations. University students, regardless of whether they live in large cities or small towns or even remote areas are taught by the same Professors and receive the same study materials. Even examinations are identical throughout the country.",
 "What kind of the Professors at University of UAF?",
 "The University utilizes the services of the very best Professors that has to offer. They belong to the best universities and other institutions of the country and are acknowledged masters of their subjects. Most of the Professors hold PhD degrees and even several Vice-Chancellors of major national universities have taught courses at the University.",
 "What if I need to ask a question from my teachers?",
 "you can ask questions at any time over the Internet using the University comprehensive Learning Management System(LMS).",
 "Is the university of UAF degree recognized?",
 "The University of UAF has been established by the Government of Pakistan.As such,its degrees are recognized by the Higher Education Commission,Islamabad.",
 "From where can I obtain the lecture handouts?",
 "Lecture Handouts are easily available through the UAF University online (http://lms.uaf.edu.pk/) and also Anailable on Bookshop of Campus. Availability of handouts is not limited to UAF students only, students and faculty from other Universities as well as the public at large can benefit from these courses and associated material.",
 "Are the courses offered by University comparable to international standards in UAF?",
 "Yes. University programs are based on curricula developed by the Higher Education Commission (HEC). The course outlines used in these curricula are based on international demands and standards.",
 "How can I get a To whom it may Concern certificate in UAF?",
 "The office of the Registrar facilitates its students to get a certificate which shows their current status of study at Unviersity in UAF, upon payment of prescribed fee.",
 "How can I get Course Contents/Syllabus of a Study/Degree Program? in UAF",
 "You can get the signed (UG-1 form) hard copy of Course Contents/Syllabus of your study in rpgram. Further you can get the soft copies of the Course Contents/Syllabus at (http://uaf.edu.pk/admissions/un/UI_form.html) and Hard copy available on Bookshop of Campus.",
 "How can I get my student status changed(Overseas to Pakistan or vice versa) in UAF?",
 "You may get your status changed by emailing at University (fsa@uaf.edu.pk) or using the University Support System.",
 "How I can change my Campus?",
 "You can Change your campus by sending e-mail at university wed site(http://web.uaf.edu.pk/) and contact the head of Department.",
 "What are the rules for semester freeze in UAF?",
 "Semester Freeze, His/Her semester fee shall not be transferred/refunded. If a student freezes semester (s) she/he can resume his/her studies from the same stage where s/he left froze. No freezing during the semester is allowed. The maximum duration of the degree program shall be the same.",
 "How can I Freeze/Unfreeze my Semester?",
 "You can freeze/unfreeze your semester by following the steps as mentioned in wed site (http://web.uaf.edu.pk/), Registrar office or e-mail at (registrar@uaf.edu.pk)to get your semester Freeze or Unfreeze.",
 "What’s the difference between a college and a university?",
 "Colleges offer only undergraduate degrees while universities offer graduate degrees as well, but the terms are often used interchangeably.",
 "who to get foreign Student Addmission in UAF?",
 "The Foreign Students’ Advisor Office (FSA) at the University of Agriculture, Faisalabad (UAF), Pakistan, is dedicated to helping foreign students with the admission process and beyond. The office promotes internationalization at UAF by increasing the number of foreign student admissions to degree programs in agriculture and related sciences. UAF strives to provide a comprehensive education that encompasses knowledge, skills, and values while also forging friendships between students’ home country and Pakistan. FSA assists interested international students with documents needed for a Pakistani visa when they start their academic journey; FSA offers academic guidance and mentorship and facilitates social events to help with cultural integration. Furthermore, we arrange activities at the university for international students providing opportunities to learn about Pakistani culture. With our support, foreign students can smoothly transition into their new lives as students in Pakistan. FSA is committed to facilitating student mobility and administering international funding awards. We aim to foster an inclusive environment for foreign students at UAF. Contact us Ph:  +92419200161-70, Ext.3806, Email: fsa@uaf.edu.pk.",
 "Work-Study Program In UAF?",
 "A form of financial assistance in which students perform work in exchange for money for their education. A number of students are working on various research projects sponsored by HEC/ Government Departments/ organizations.",
 "Student Loan Scheme in UAF?",
 "Students of this University also apply to National Bank of Pakistan to get interest free loan in order to support their education. Students are facilitated in processing their applications to NBP, University Branch. Loan Scholarship Scheme is also underway for financially weak students.",
 "Good bye",
 "Good bye,thanks for visiting,Have a nice day.",
 "Goodbye",
 "Goodbye,thanks for visiting,Have a nice day.",
 "bye",
 "bye,thanks for visiting,Have a nice day.",
 "goodbye",
 "goodbye,thanks for visiting,Have a nice day.",
 "Allha Hafiz",
 "Allha hafiz,thanks for visiting,Have a nice day.",
 "Allha hafiz",
 "Allha hafiz,thanks for visiting,Have a nice day.",
]